### PR TITLE
Add `chrisgrieser/nvim-origami`

### PR DESCRIPTION
**Pull request by chrisgrieser**

### CODE REVIEW

**Comment by neurosnap** [comment]
I just merged this plugin, do we still need this PR?

**Comment by chrisgrieser** [comment]
Oh, then of course not. How come you already have the plugin?

**Comment by neurosnap** [comment]
https://github.com/neurosnap/neovimcraft/pull/440

**Comment by chrisgrieser** [comment]
oh, I see. There was a hickup on my end, thought thought the PR didn't go throug, but apparently it did

**Pull request closed without merging**
