### PR TITLE
feat: add Massolari/forem.nvim

### PR DESCRIPTION
**Pull request by Massolari**

### CODE REVIEW

**Review by neurosnap — CHANGES_REQUESTED** [review]
Thanks for the contribution!  Please add this entry to `manual.json` using the `yarn resource` command

**Comment by Massolari** [comment]
Oh, I'm sorry I missed that.
I've read from the website that I might just add the plugin to resource.json I didn't even read the documentation about contributing.

**Comment by Massolari** [comment]
When I ran `yarn resource` and tried to add my repo, it told me that it already existed in resources.json and exited.
So, I've deleted the entry in resources.json and ran `yarn resource` again, this time everything went as expected, but it just added in manual.json, not in resources.json.
Is that okay to have the entry just in manual.json?

**Comment by neurosnap** [comment]
Yep that's right!  `resources.json` is only for the automated scraping.  We combine `manual.json` and `resources.json` together when generating the site.

I'll push a change to the faq on the site so it's more clear.

**Review by neurosnap — APPROVED** [review]

**Pull request merged**
