### PR TITLE
add glepnir/lspsaga.nvim

### PR DESCRIPTION
**Pull request by kiryph**
- Add glepnir/lspsaga.nvim

### CODE REVIEW

**Review by neurosnap — CHANGES_REQUESTED** [review]
Could you please look at the tags currently available and use them here.

**Comment by kiryph** [comment]
@neurosnap Yes, I can do this. 

I am wondering how well-chosen and intentionally the current set of tags is:

- There is a tag for `neovim-0.5`, but none for `neovim-0.6`, `neovim-0.7`, ...  
  IMHO this tags needs maintenance and I would remove it completely.
- A specific tag `lsp-installer`, but no general `lsp` tag. There are now more plugins dedicated for `language-server-protocol` which are not lsp installer.    
  Plugin [`lsp_signature.nvim`](https://github.com/ray-x/lsp_signature.nvim) and other lsp plugins have the general tag `neovim-0.5` which can become outdated. E.g. current `lsp_signature.nvim` requires nevom-0.6.1.
- General tag `debugging` but no tag for `debug-adapter-protocol`/`dap`
- Specific tags `lua-colorscheme`, `tree-sitter-supported-colorscheme` but not a general tag `colorscheme`.
- filetypes
  - `latex`, `markdown` and the combination of `markdown/latex` as well exist
  - but others could be helpful as well `ft-html`, `ft-rust`, `ft-go`, `ft-python`,...  
  The general tag `programming-languages-support` is not helpful for *ft-specific* plugins because users will usually look for their language not all languages. For instance, when I look for rust plugins, I am not interested in html plugins.
- Why has the plugin `nvim-treesitter-textobjects` the tag `syntax` but not `treesitter-based` ?
- ...

**Comment by neurosnap** [comment]
Most of these tags are derived from https://github.com/rockerBOO/awesome-neovim

**Comment by kiryph** [comment]
Following relevant “tags” exist on https://github.com/rockerBOO/awesome-neovim
but not here

- `lsp`
- `terminal-integration`

IMHO tags should not be like the folders in a file system or headers in a document, ie. each element can only be in one folder/chapter but can have several tags which makes using this markdown file as reference not ideal.

**Comment by neurosnap** [comment]
Closing for now.  Feel free to reopen with conflicts resolved

**Pull request closed without merging**
